enquete-app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enquete/', include('enquete.urls')),
]

enquete-app/enquete/urls.py
from django.urls import path

from . import views

app_name = 'enquete'

urlpatterns = [
    # アンケート一覧画面
    path('', views.EnqueteListView.as_view(), name='list'),
    # アンケート作成画面
    path('create/', views.EnqueteCreateView.as_view(), name='create'),
    path('<int:page_num>/', views.EnqueteListView.as_view(), name='page'),
    # アンケート詳細画面
    path('<str:uuid>/', views.EnqueteDetailView.as_view(), name='detail'),
    # アンケート回答画面
    path('<str:uuid>/answer/', views.EnqueteAnswerView.as_view(), name='answer'),
    # アンケート集計画面
    path('<str:uuid>/totalize/',
         views.EnqueteTotalizeView.as_view(), name='totalize'),
    # アンケート回答修正画面
    path('<str:uuid>/<int:member_id>/',
         views.EnqueteAnswerUpdateView.as_view(), name='answer_update'),
]

enquete-app/enquete/models.py
from django.db import models


class Enquete(models.Model):
    """
    アンケートテーブル
    項目:
        アンケートID: uuid4で払い出される
        アンケート名: アンケートの名前
    """
    enquete_id = models.CharField(max_length=512)
    enquete_name = models.CharField(max_length=512)

    def __str__(self):
        return self.enquete_name


class Question(models.Model):
    """
    質問テーブル
    項目:
        質問文: 質問の文章
        質問タイプ: テキスト・セレクトボックス・ラジオボタンのいずれか
    """
    question_text = models.CharField(max_length=512)
    question_type = models.CharField(max_length=512)

    def __str__(self):
        return '{} {}'.format(self.question_text, self.question_type)


class Choice(models.Model):
    """
    選択肢テーブル
    項目:
        選択肢名: セレクトボックス・ラジオボタンの質問の選択肢名
    """
    choice_name = models.CharField(max_length=512)

    def __str__(self):
        return self.choice_name


class Member(models.Model):
    """
    部員テーブル
    項目:
        部員名: アンケート回答をする部員名
    """
    member_name = models.CharField(max_length=512)

    def __str__(self):
        return self.member_name


class EQ(models.Model):
    """
    アンケートテーブルと質問テーブルの中間テーブル
    項目:
        アンケートオブジェクト: 外部キーとしてアンケートオブジェクトを保持
        質問オブジェクト: 外部キーとして質問オブジェクトを保持
    """
    E_obj = models.ForeignKey(Enquete, on_delete=models.CASCADE)
    Q_obj = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return '{} {}'.format(self.E_obj.enquete_name, self.Q_obj.question_text)


class QC(models.Model):
    """
    質問テーブルと選択肢テーブルの中間テーブル
    項目:
        質問オブジェクト: 外部キーとして質問オブジェクトを保持
        選択肢オブジェクト: 外部キーとして選択肢オブジェクトを保持
    """
    Q_obj = models.ForeignKey(Question, on_delete=models.CASCADE)
    C_obj = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return '{} {}'.format(self.Q_obj.question_text, self.C_obj.choice_name)


class QM(models.Model):
    """
    質問テーブルと部員テーブルの中間テーブル
    項目:
        質問オブジェクト: 外部キーとして質問オブジェクトを保持
        部員オブジェクト: 外部キーとして部員オブジェクトを保持
        回答内容: 質問項目に対する部員の回答内容を保持
    """
    Q_obj = models.ForeignKey(Question, on_delete=models.CASCADE)
    M_obj = models.ForeignKey(Member, on_delete=models.CASCADE)
    answer = models.CharField(max_length=512)

    def __str__(self):
        return '{} {}'.format(self.Q_obj.question_text, self.M_obj.member_name)

enquete-app/enquete/forms.py
from django import forms

from . import models

select_data = [
    ('none', '選択してください'),
    ('text', 'テキストボックス'),
    ('select', 'セレクトボックス'),
    ('radio', 'ラジオボタン'),
]


class CreateFormTemplate(object):
    """
    動的にフォームを作成する際に使用する、設定をまとめたクラス
    """
    DEFAULT_CHOICE = ('none', '選択してください')

    def create_text_form(self, max_length=512):
        """
        テキスト形式のフォーム属性を用意する
        Args:
            max_length (int): 最大文字長
        """
        text_form = forms.CharField(
            max_length=max_length
        )
        return text_form

    def create_select_form(self, choices=None):
        """
        セレクトボタン形式のフォーム属性を用意する
        Args:
            choices (list): 選択肢のタプルのリスト
        """
        select_form = forms.ChoiceField(
            choices=choices,
        )
        return select_form

    def create_radio_form(self, choices=None):
        """
        ラジオボタン形式のフォーム属性を用意する
        Args:
            choices (list): 選択肢のタプルのリスト
        """
        radio_form = forms.ChoiceField(
            choices=choices,
            widget=forms.RadioSelect(),
        )
        return radio_form


class CreateEnqueteForm(forms.Form):
    """
    アンケート作成画面の入力フォーム

    Attributes:
        enquete_name (:obj:`form`): アンケート名を入力するフォーム
        question_text (:obj:`form`): 質問文を入力するフォーム
    """

    def __init__(self, *args, **kwargs):
        """
        bootstrap用にform-controlクラスを追加
        """
        super(CreateEnqueteForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

    enquete_name = forms.CharField(
        label='アンケートタイトル',
        max_length=512,
        required=False,
    )
    question_text = forms.CharField(
        label='質問文',
        max_length=512,
        required=False
    )
    question_type = forms.ChoiceField(
        label='回答タイプ',
        choices=select_data,
        required=False,
    )
    choice_name = forms.CharField(
        label='選択肢',
        required=False,
        max_length=512,
    )


class MemberForm(forms.Form):
    """
    アンケート回答画面にて、回答者を選択するフォーム
    Attributes:
        member_name (:`obj`:form): アンケートの回答者を選択するフォーム
    """

    def __init__(self, *args, **kwargs):
        """
        bootstrap用にform-controlクラスを追加
        """
        super(MemberForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

    member_name = forms.ModelChoiceField(
        label='回答者',
        queryset=models.Member.objects.all(),
        empty_label='回答者を選択してください',
    )


class TextForm(forms.Form):
    """
    アンケート回答画面にて使用する、text形式のフォーム
    answer属性は動的に生成する。

    Attributes:
        answer (:`obj`:form): テキスト形式の回答フォーム
    """

    def __init__(self, *args, **kwargs):
        """
        bootstrap用にform-controlクラスを追加
        """
        super(TextForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class SelectForm(forms.Form):
    """
    アンケート回答画面にて使用する、select形式のフォーム
    answer属性は動的に生成する。

    Attributes:
        answer (:`obj`:form): テキスト形式の回答フォーム
    """

    def __init__(self, *args, **kwargs):
        """
        bootstrap用にform-controlクラスを追加
        """
        super(SelectForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class RadioForm(forms.Form):
    """
    アンケート回答画面にて使用する、radio形式のフォーム
    answer属性は動的に生成する。

    Attributes:
        answer (:`obj`:form): テキスト形式の回答フォーム
    """

    def __init__(self, *args, **kwargs):
        """
        bootstrap用にform-controlクラスを追加
        """
        super(RadioForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-check-input"

enquete-app/enquete/views.py
from django.shortcuts import render
from django.views.generic import View
from django.core.paginator import Paginator

import uuid

from enquete.lib.views_utils import assemble_data_for_totalize_graphs
from enquete.lib.views_utils import make_color
from enquete.lib.views_utils import assemble_questions
from enquete.lib.views_utils import assemble_questions_with_answer
from enquete.lib.views_utils import answer_enquete
from enquete.lib.views_utils import update_enquete
from . import models
from . import forms


class EnqueteListView(View):
    """
    アンケート一覧画面
    """

    def __init__(self):
        self.PAGENATE = 10

    def get(self, request, *args, **kwargs):
        """
        機能
        ・IDリンク付き一覧表示
        ・ページング　10件ごと
        """
        page_num = kwargs.get('page_num', 1)

        enq_list = models.Enquete.objects.all()
        pagenater = Paginator(enq_list, self.PAGENATE)

        page_data = pagenater.get_page(page_num)

        context_data = {
            'data': page_data,
            'page_obj': page_data,
            'page_title': 'アンケート一覧画面',
            'headers': ['アンケートID', 'アンケート名'],
        }
        return render(request, 'enquete/enquete_list.html', context_data)


class EnqueteCreateView(View):
    """
    アンケート作成画面
    """

    def __init__(self):
        self.PAGE_TITLE = 'アンケート作成画面'
        self.QUESTION_TEXT = 'question_text'
        self.QUESTION_TYPE = 'question_type'
        self.CHOICE_NAME = 'choice_name'
        self.IS_SUCCESS = False

    def get(self, request, *args, **kwargs):
        """
        機能
        ・アンケート名の入力
        ・任意の質問項目の追加
        """
        context_data = {
            'page_title': self.PAGE_TITLE,
            'forms': forms.CreateEnqueteForm(),
            'is_success': self.IS_SUCCESS,
        }
        return render(request, 'enquete/enquete_create.html', context_data)

    def post(self, request, *args, **kwargs):
        """
        機能
        ・入力された内容の登録
            -アンケート
            -質問項目
        """
        # アンケートの作成を行う
        self.IS_SUCCESS = self._create_enquete(request)

        context_data = {
            'page_title': self.PAGE_TITLE,
            'forms': forms.CreateEnqueteForm(request.POST or None),
            'is_success': self.IS_SUCCESS,
        }
        print(request.POST)
        return render(request, 'enquete/enquete_create.html', context_data)

    def _create_enquete(self, request):
        """
        アンケートの作成を行う
        """
        is_success = False
        # Enqueteレコード作成
        enquete_id = uuid.uuid4()
        enquete_name = request.POST.get('enquete_name', None)
        enquete_obj = models.Enquete(
            enquete_id=enquete_id,
            enquete_name=enquete_name,
        )
        enquete_obj.save()

        total_q_num = request.POST.get('total_question_num', 1)
        for q_num in range(1, int(total_q_num) + 1):
            # 取得するキーの組み立て
            question_text_str = self.QUESTION_TEXT + str(q_num)
            question_type_str = self.QUESTION_TYPE + str(q_num)
            choice_name_str = self.CHOICE_NAME + str(q_num)

            # 質問項目ごとの情報を取得
            question_text = request.POST.get(question_text_str)
            question_type = request.POST.get(question_type_str)
            choice_names = request.POST.getlist(choice_name_str)

            # Questionレコードの作成
            question_obj = models.Question(
                question_text=question_text,
                question_type=question_type,
            )
            question_obj.save()

            # EQレコードの作成
            EQ_obj = models.EQ(
                E_obj=enquete_obj,
                Q_obj=question_obj,
            )
            EQ_obj.save()

            # Choiceレコードの作成
            for choice_name in choice_names:
                choice_obj = models.Choice(
                    choice_name=choice_name
                )
                choice_obj.save()

                # QCレコードの作成
                QC_obj = models.QC(
                    Q_obj=question_obj,
                    C_obj=choice_obj,
                )
                QC_obj.save()

        is_success = True
        return is_success


class EnqueteDetailView(View):
    """
    アンケート詳細画面
    """

    def __init__(self):
        self.PAGE_TITLE = 'アンケート詳細画面'

    def get(self, request, *args, **kwargs):
        """
        機能
        ・アンケートの詳細情報を表示する
        ・アンケートの回答更新画面へのリンクを提供する
        """
        # アンケートの詳細情報を保持する
        # enquete_details = [{
        #   'member_name': '石井',
        #   'answer': []
        #   },
        #   ....
        # ]

        # アンケートidを取得
        enquete_id = kwargs.get('uuid', None)

        # 対象のアンケートを取得
        enquete_obj = models.Enquete.objects.get(enquete_id=enquete_id)
        eqs = enquete_obj.eq_set.all()

        # テーブルのヘッダーを作成する
        headers = ['回答者', ]
        for eq in eqs:
            headers.append(eq.Q_obj.question_text)

        # アンケートの回答者を取得
        members_obj = []
        for eq in eqs:
            qms = eq.Q_obj.qm_set.all()
            for qm in qms:
                if qm.M_obj in members_obj:
                    continue
                members_obj.append(qm.M_obj)

        # アンケートの質問を取得
        questions_obj = []
        for eq in eqs:
            questions_obj.append(eq.Q_obj)

        # 各回答者の回答を取得し、enquete_detailに詰める
        enquete_details = []
        for member_obj in members_obj:
            enquete_detail = {}
            answers = []
            for question_obj in questions_obj:
                qm = models.QM.objects.get(
                    Q_obj=question_obj, M_obj=member_obj)
                answers.append(qm.answer)

            enquete_detail['member_obj'] = member_obj
            enquete_detail['answers'] = answers

            enquete_details.append(enquete_detail)

        context_data = {
            'page_title': self.PAGE_TITLE,
            'enquete_id': enquete_id,
            'headers': headers,
            'enquete_details': enquete_details,
        }
        return render(request, 'enquete/enquete_detail.html', context_data)


class EnqueteAnswerView(View):
    """
    アンケート回答画面
    """

    def __init__(self):
        self.PAGE_TITLE = 'アンケート回答画面'
        self.IS_SUCCESS = False

    def get(self, request, *args, **kwargs):
        """
        機能
        ・アンケートへの回答を行う
        """
        # アンケートidを取得
        enquete_id = kwargs.get('uuid', None)

        # 対象のアンケートを取得
        enquete_obj = models.Enquete.objects.get(enquete_id=enquete_id)

        # アンケートに紐づく質問を組み立て
        questions = assemble_questions(enquete_obj)

        context_data = {
            'page_title': self.PAGE_TITLE,
            'enquete_obj': enquete_obj,
            'questions': questions,
            'member_form': forms.MemberForm(),
            'is_success': self.IS_SUCCESS,
        }

        return render(request, 'enquete/enquete_answer.html', context_data)

    def post(self, request, *args, **kwargs):
        """
        機能
        ・アンケートへの回答を登録する
        """
        # TODO: 失敗した場合の例外処理を入れる
        self.IS_SUCCESS = True

        # アンケートidを取得
        enquete_id = kwargs.get('uuid', None)
        member_id = request.POST.get('member_name')

        # 対象のアンケートを取得
        enquete_obj = models.Enquete.objects.get(enquete_id=enquete_id)
        # 回答者を取得
        member_obj = models.Member.objects.get(id=member_id)

        # アンケートの回答内容を保存
        self.IS_SUCCESS = answer_enquete(enquete_obj, member_obj, request)

        # アンケートに紐づく質問を組み立て
        questions = assemble_questions(enquete_obj)

        member_form = forms.MemberForm()

        context_data = {
            'page_title': self.PAGE_TITLE,
            'enquete_obj': enquete_obj,
            'questions': questions,
            'member_form': member_form,
            'is_success': self.IS_SUCCESS,
        }

        return render(request, 'enquete/enquete_answer.html', context_data)


class EnqueteAnswerUpdateView(View):
    """
    アンケートの回答更新画面
    """

    def __init__(self):
        self.PAGE_TITLE = 'アンケート回答更新画面'
        self.IS_SUCCESS = False

    def get(self, request, *args, **kwargs):
        """
        機能
        ・一度回答したアンケートへの回答を更新する
        """
        # アンケートidと回答者idを取得
        enquete_id = kwargs.get('uuid', None)
        member_id = kwargs.get('member_id', None)

        # 対象のアンケートと回答者レコードを取得
        enquete_obj = models.Enquete.objects.get(enquete_id=enquete_id)
        member_obj = models.Member.objects.get(id=member_id)

        # アンケートに紐づく質問を組み立て
        questions = assemble_questions_with_answer(enquete_obj, member_obj)

        # MemberFormの初期化を行う
        # 初期値を設定するにはインスタンス化するタイミングで、
        # formの属性名をキーに、初期値をバリューとして定義して渡す必要がある
        initial = {
            'member_name': member_id,
        }
        member_form = forms.MemberForm(initial=initial)

        context_data = {
            'page_title': self.PAGE_TITLE,
            'enquete_obj': enquete_obj,
            'member_obj': member_obj,
            'questions': questions,
            'member_form': member_form,
            'is_success': self.IS_SUCCESS,
        }

        return render(request, 'enquete/enquete_answer_update.html', context_data)

    def post(self, request, *args, **kwargs):
        """
        機能
        ・入力された内容で回答を更新する
        """
        # アンケートidと回答者idを取得
        enquete_id = kwargs.get('uuid', None)
        member_id = kwargs.get('member_id', None)

        # 対象のアンケートと回答者レコードを取得
        enquete_obj = models.Enquete.objects.get(enquete_id=enquete_id)
        member_obj = models.Member.objects.get(id=member_id)

        # アンケートの回答内容を保存
        self.IS_SUCCESS = update_enquete(enquete_obj, member_obj, request)

        # アンケートに紐づく質問を組み立て
        questions = assemble_questions(enquete_obj)

        member_form = forms.MemberForm()

        context_data = {
            'page_title': self.PAGE_TITLE,
            'enquete_obj': enquete_obj,
            'member_obj': member_obj,
            'questions': questions,
            'member_form': member_form,

enquete-app/enquete/templates/enquete/enquete_answer_update.html
{% extends 'base/base.html' %}

{% block title %}
<title>
  {{ page_title }}
</title>
{% endblock %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'enquete:list' %}">アンケート一覧</a></li>
    <li class="breadcrumb-item"><a href="{% url 'enquete:detail' enquete_obj.enquete_id %}">アンケート詳細</a></li>
    <li class="breadcrumb-item active">アンケート更新</li>
  </ol>
</nav>
{% endblock %}

{% block page_title %}
{{ page_title }}
{% endblock %}

{% block main %}
{% if is_success %}
<div class="alert alert-success" role="alert">
  アンケートの回答を更新しました。
  ご回答ありがとうございました。
</div>
{% endif %}

<h2>
  {{ enquete_obj.enquete_name }}
</h2>

<form action="{% url 'enquete:answer_update' enquete_obj.enquete_id member_obj.id %}" method="POST">
  {% csrf_token %}
  <label class="question-text">
    回答者：
  </label>
  {{ member_form.member_name }}
  {% for question in questions %}
  <label class="question-text">
    {{ question.question_text }}
  </label>
  {{ question.question_form }}
  {% endfor %}
  <div class="button-field">
    <button type="submit" class="btn btn-primary" id="id_answer">更新する</button>
  </div>
</form>
{% endblock %}

{% block script %}
<script>
  // radioボタンのulタグのclassをform-checkに変更する
  $('ul').removeClass('form-check-input');
  $('ul').addClass('form-check');

  // 回答者を選択不可にする
  // これを更新可能にするといろいろ考えなきゃいけなくなるので面倒
  $('#id_member_name').prop('disabled', true);

  // label属性を全部取得して、必要ないラベルを削除する
  $('label').each(function (i, element) {
    if ($(element).text().match('Answer')) {
      $(element).remove();
    }
  })
</script>
{% endblock %}

enquete-app/enquete/templates/enquete/enquete_create.html
{% extends 'base/base.html' %}

{% block title %}
<title>
  {{ page_title }}
</title>
{% endblock %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'enquete:list' %}">アンケート一覧</a></li>
    <li class="breadcrumb-item active">アンケート作成</li>
  </ol>
</nav>
{% endblock %}

{% block page_title %}
{{ page_title }}
{% endblock %}

{% block hidden %}
<!-- 質問追加用のhidden -->
<div class="card" id="question-hidden" hidden>
  <div class="card-header" id="heading-">
    <h2 class="mb-0">
      <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#base-question-"
        aria-expanded="false" aria-controls="base-question-">
        質問項目　＃
      </button>
    </h2>
  </div>
  <div id="base-question-" class="collapse show hidden-body" aria-labelledby="heading-"
    data-parent="#question-accordion">
    <div class="card-body">
      {{ forms.question_text.label_tag }}
      {{ forms.question_text }}
      {{ forms.question_text.errors }}

      {{ forms.question_type.label_tag }}
      {{ forms.question_type }}
      {{ forms.question_type.errors }}

      <div id="choice-field">
        {{ forms.choice_name.label_tag }}
        <div class="form-inline add-field">
          {{ forms.choice_name }}
          {{ forms.choice_name.errors }}
          <button type="button" class="btn btn-info add">+</button>
          <button type="button" class="btn btn-info del">-</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}


<!-- djangoのformにbootstrapを設定 -->
<!-- http://strkita.hatenablog.com/entry/2017/08/17/232712 -->
{% block main %}
{% if is_success %}
<div class="alert alert-success" role="alert">
  アンケートの作成に成功しました。
  続けて新しいアンケートを作成できます。
</div>
{% endif %}

<form action="{% url 'enquete:create' %}" method="POST">
  {% csrf_token %}
  <!-- 最新の質問番号を保持 -->
  <input type="hidden" name="total_question_num" value="1" id="id_total_question_num">
  <!-- アンケート名 -->
  <div class="form-group">
    {{ forms.enquete_name.label_tag }}
    {{ forms.enquete_name }}
    {{ forms.enquete_name.errors }}
  </div>
  <!-- 質問項目 -->
  <div class="accordion" id="question-accordion">
    <div class="card">
      <div class="card-header" id="heading-1">
        <h2 class="mb-0">
          <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#question-1"
            aria-expanded="true" aria-controls="question-1">
            質問項目　＃1
          </button>
        </h2>
      </div>
      <div id="question-1" class="collapse show" aria-labelledby="heading-1" data-parent="#question-accordion">
        <div class="card-body">
          {{ forms.question_text.label_tag }}
          {{ forms.question_text }}
          {{ forms.question_text.errors }}

          {{ forms.question_type.label_tag }}
          {{ forms.question_type }}
          {{ forms.question_type.errors }}

          <div id="choice-field">
            {{ forms.choice_name.label_tag }}
            <div class="form-inline add-field">
              {{ forms.choice_name }}
              {{ forms.choice_name.errors }}
              <button type="button" class="btn btn-info add">+</button>
              <button type="button" class="btn btn-info del">-</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="button-field">
    <button type="button" class="btn btn-info" id="id_add_question">質問の追加</button>
    <button type="submit" class="btn btn-primary" id="id_create_enquete">アンケート作成</button>
  </div>
</form>
{% endblock %}

{% block script %}
<script>

  // id, nameにQ_numを追加
  $(document).ready(function () {
    $('form #id_question_text').attr('name', 'question_text1')
    $('form #id_question_text').attr('id', 'id_question_text1')
    $('form #id_question_type').attr('name', 'question_type1')
    $('form #id_question_type').attr('id', 'id_question_type1')
    $('form #id_choice_name').attr('name', 'choice_name1')
    $('form #id_choice_name').attr('id', 'id_choice_name1')

    // add-fieldの中身を押せないようにする
    $('.add-field').each(function (i, element) {
      $(element).children('input').prop('disabled', true);
      $(element).children('button').prop('disabled', true);
    })
  })

  // セレクトボックスとラジオボタンを選択した時のみ、選択肢を入力できるようにする
  $('select').change(function () {
    var value = $(this).val()

    console.log(value)
    if (value == 'select' || value == 'radio') {
      console.dir($(this).next().find('.add-field').children('input'))
      $(this).next().find('.add-field').children('input').prop('disabled', false)
      $(this).next().find('.add-field').children('button').prop('disabled', false)
    }
    else {
      $(this).next().find('.add-field').children('input').prop('disabled', true)
      $(this).next().find('.add-field').children('button').prop('disabled', true)
    }
  })

  $('#id_add_question').on('click', function () {

    // hiddenの質問項目を複製
    let new_question = $('#question-hidden').clone(true)
    new_question.removeAttr('hidden')
    new_question.removeAttr('id')

    // 新しいIDを設定
    Q_num = $('#id_total_question_num').val()
    Q_num = parseInt(Q_num, 10) + 1
    $('#id_total_question_num').val(Q_num)

    let new_id = 'base-question-' + Q_num;

    // アコーディオンを動作させるための設定
    new_question.find('.card-header').attr('id', 'heading-' + Q_num);
    new_question.find('.mb-0 button').attr('data-target', '#' + new_id)
    new_question.find('.mb-0 button').attr('aria-controls', new_id)
    new_question.find('.mb-0 button').html('質問項目　#' + Q_num)
    new_question.find('.hidden-body').attr('id', new_id);
    new_question.find('.hidden-body').attr('aria-labelledby', 'heading-' + Q_num);

    // formのidを更新する
    new_question.find('#id_question_text').attr('name', 'question_text' + Q_num)
    new_question.find('#id_question_text').attr('id', 'id_question_text' + Q_num)
    new_question.find('#id_question_type').attr('name', 'question_type' + Q_num)
    new_question.find('#id_question_type').attr('id', 'id_question_type' + Q_num)
    new_question.find('#id_choice_name').attr('name', 'choice_name' + Q_num)
    new_question.find('#id_choice_name').attr('id', 'id_choice_name' + Q_num)

    new_question.appendTo('#question-accordion')
  })

  // 選択肢の入力項目を表示させる  
  $('#id_question_type').change(function () {
    if ($(this).val() !== 'text') {
      $(this).parent().parent().find('#id_choice_name').removeClass("hide")
    }
    else {
      $(this).parent().parent().find('#id_choice_name').addClass("hide")
    }
  })

  // 選択肢の追加
  $('.add').on("click", function () {
    $(this).parent().clone(true).insertAfter($(this).parent());
  });
  $('.del').on("click", function () {
    var target = $(this).parent();
    if (target.parent().children().length > 2) {
      target.remove();
    }
  });

</script>
{% endblock %}